FROM golang:alpine3.13 as builder
WORKDIR /go/src/app
RUN apk add --no-cache git \
&& git clone https://github.com/muxfd/multipath-udp.git . \
&& go build -o /receiver cmd/receiver/main.go && rm -rf /go/src/app
FROM alpine:3.14
COPY --from=builder /receiver /receiver
EXPOSE 1985/udp
ENTRYPOINT ["/receiver"]