name: Docker images build

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: nginx-rtmp-srt-transmuxer 
            dockerfile: jetsonbuild/Dockerfile.nginx-rtmp-srt-transmuxer
            tags: |-
              rnsc/jetson-nano-nginx-rtmp-srt-transmuxer:latest
              rnsc/jetson-nano-nginx-rtmp-srt-transmuxer:1.0.0
          - name: multipath-udp-sender 
            dockerfile: jetsonbuild/Dockerfile.multipath-udp-sender
            tags: |-
              rnsc/jetson-nano-multipath-udp-sender:latest
              rnsc/jetson-nano-multipath-udp-sender:1.0.0
          - name: belabox
            dockerfile: jetsonbuild/Dockerfile.belabox
            tags: |-
              rnsc/jetson-nano-belabox:latest
              rnsc/jetson-nano-belabox:1.0.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: jrei
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: "linux/amd64"
          push: true
          tags: ${{ matrix.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
