name: Docker images build - linuxbuild

on:
  push:
    branches: ['main']
    paths:
      - 'linuxbuild/**'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - name: belabox-srtla-receiver 
            dockerfile: linuxbuild/Dockerfile.belabox-srtla-receiver
            tags: |-
              rnsc/jetson-nano-belabox-srtla-receiver:latest
              rnsc/jetson-nano-belabox-srtla-receiver:1.2.0
          - name: noalbs-srtla
            dockerfile: linuxbuild/Dockerfile.noalbs-srtla
            tags: |-
              rnsc/noalbs-srtla:latest
              rnsc/noalbs-srtla:1.2.0
          - name: noalbs-sls
            dockerfile: linuxbuild/Dockerfile.noalbs-sls
            tags: |-
              rnsc/noalbs-sls:latest
              rnsc/noalbs-sls:1.2.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: rnsc
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v2
        with:
          context: ./linuxbuild
          file: ${{ matrix.dockerfile }}
          platforms: "linux/amd64"
          push: true
          tags: ${{ matrix.tags }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
